name: "Deploy my challenge 1"

on:
    push:
        branches: 
            - dev
 
jobs:
    deployment-in-dev-env:
        runs-on: ubuntu-latest
        permissions: 
            contents: 'read'
            id-token: 'write'
        
        steps:
            - name: checkout my code
              uses: actions/checkout@v3