name: "Deploy my challenge 1"

on:
    push:
        branches:
            - dev
        paths: 
            - 'challenge-1-cicd/**'

jobs:
    deployment-in-dev-env:
        runs-on: ubuntu-latest
        permissions: 
            contents: 'read'
            id-token: 'write'

        steps:
            - name: checkout my code
              uses: actions/checkout@v3

            - id: 'auth'
              name: 'Authenticate to GCP DEV project'
              uses: 'google-github-actions/auth@v1'
              with:
                  token_format: 'access_token'
                  workload_identity_provider: 'projects/432600233474/locations/global/workloadIdentityPools/mypoolid-devproject-1/providers/myproviderid-devproject-1'
                  service_account: sa-dev-4-challenge-1-cicd@dev-project-406720.iam.gserviceaccount.com

            - name: 'Initializing terraform'
              run: |
                cd $GITHUB_WORKSPACE/challenge-1-cicd/terraform
                terraform init
                terraform apply -auto-approve
              env:
                TF_VAR_sa_dev: "sa-dev-4-challenge-1-cicd@dev-project-406720.iam.gserviceaccount.com"

    verify-deployment-in-dev-env:
        runs-on: ubuntu-latest

        needs: deployment-in-dev-env
        if: success()

        permissions: 
          contents: 'read'
          id-token: 'write'
        
        steps:
          - name: checkout my code
            uses: actions/checkout@v3
            
          - id: 'auth'
            name: 'Authenticate to GCP DEV project'
            uses: 'google-github-actions/auth@v1'
            with:
              token_format: 'access_token'
              workload_identity_provider: 'projects/432600233474/locations/global/workloadIdentityPools/mypoolid-devproject-1/providers/myproviderid-devproject-1'
              service_account: sa-dev-4-challenge-1-cicd@dev-project-406720.iam.gserviceaccount.com

          - name: 'setup my cloud SDK'
            uses: 'google-github-actions/setup-gcloud@v1'
          
          - name: 'test the deployed cloud function'
            run: |
              gsutil cp $GITHUB_WORKSPACE/challenge-1-cicd/testing/testFile.txt gs://cf_source_bucket_4_challenge-1-cicd/test_file1_trigger.txt
          
          - name: 'validate the testing'
            id: status
            run: |
              if gsutil stat gs://cf_target_bucket_4_challenge-1-cicd/processed_file.txt 
              then
                export status_val=pass
                echo "file exist"
                echo "value of status_val is: $status_val"
              else
                export status_val=fail
                echo "file doesnt exist"
                echo "value of status_val is: $status_val"
              fi
              
              echo "status_val=$status_val" >> $CI_JOB_NAME.env
          
        outputs:
            status_val: ${{steps.verify-deployment-in-dev-env.outputs.status_val}}
                   

    code-merge-in-prod-env:
      runs-on: ubuntu-latest
      needs: verify-deployment-in-dev-env
      if: success()

      steps:
        - name: checkout code
          uses: actions/checkout@v2

        - name: setup GIT
          run: |
            git config user.name "Luffy"
            git config user.email "naruto_blablabla@gmail.com"

        - name: Merge code from dev to test
          run: |
            git checkout test
            git pull origin dev
            git push origin test
