name: Sync multiple branches
on:
  push:
    branches:
      - test3
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@master
    
      - name: check the current branch
        run: |
          echo "Merge is now starting."
          git clone -b test4 https://github.com/maran281/challenge_repository.git
          git checkout test4
          git merge test3
        