name: Merge test3 to test4

on:
  push:
    branches:
      - test3

jobs:
  merge-to-test4:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          echo "hi"
