name: Merge test3 to test4

on:
  push:
    branches:
      - test3

jobs:
  merge-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Merge test3 into test4
        run: |
          current_directory=$(pwd)
          echo "1 current directory is $current_directory"
          git init
          git config user.email "maran281@github.com"
          git clone -b test3 https://github.com/maran281/challenge_repository.git
          echo *
          echo "step2"
          cd challenge_repository
          git checkout test4
          git merge test3
 #         git checkout test4
 #         echo "step4"
 #         git merge test3
