name: Merge test3 to test4

on:
  push:
    branches:
      - test3

jobs:
  merge-to-test4:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Merge test3 to test4
        run: |
          git checkout test4
          git merge --no-ff ${{ github.sha }}
          git push origin test4
