name: Merge Code Between Branches

on:
  push:
    branches:
      - main
      - feature/*

jobs:
  merge-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Merge feature branch
        run: git merge ${{ github.event.ref }}

      - name: Push changes to main branch
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git push origin main
