name: Merge test into test2

on:
  push:
    branches:
      - test

jobs:
  merge-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge test into test2
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git checkout test
          git merge --no-ff ${{ github.sha }}
          git push origin test2
