name: "testing variable creation and sharing within a job"

on:
    push:
        branches: 
            - dev
        paths: 
            - 'testFolder/**'

jobs:
    testing_started:
        runs-on: ubuntu-latest
        
        env:
            jobEnvVar_one: 'v1'
            jobEnvVar_two: 'v2'
        
        steps:
            - name: checkout my code
              uses: actions/checkout@v3
            
            - name: set and check the a STEPS's env variable
              env:
                myVar1: "hi_Manoj"
              run: |
                echo "value of step's env variable is: $myVar1"
            
            - name: set and check the JOBS's env variable
              run: |
                echo "value of job's env variable 'jobEnvVar_one' is: $jobEnvVar_one"
                echo "value of job's env variable 'jobEnvVar_two' is: $jobEnvVar_two"

            - name: set and check variables between the steps within a job
              id: step_1
              run: |
                echo "var_between_jobs_1=var_one" >> $GITHUB_ENV
                echo "var_between_jobs_2=var_two" >> $GITHUB_ENV

            - name: set and check variables between the steps within a job
              id: step_2
              run: |
                echo " value of var_between_jobs_1 is: ${{env.var_between_jobs_1}}"
                echo " value of var_between_jobs_2 is: ${{env.var_between_jobs_2}}"
