name: "testing variable creation and sharing within a job"

on:
    push:
        branches: 
            - dev
        paths: 
            - 'testFolder/**'

jobs:
    testing_started:
        runs-on: ubuntu-latest
        
        env:
            jobEnvVar_one: 'v1'
            jobEnvVar_two: 'v2'
        
        steps:
            - name: checkout my code
              uses: actions/checkout@v3
            
            - name: set and check the a step's env variable
              id: 'setVariable'
              env:
                myVar1: "hi_Manoj"
              run: |
                echo "value of step's env variable is: $myVar1"
            
            - name: set and check the job's env variable
              run: |
                echo "value of job's env variable 1 is: $jobEnvVar_one"
                echo "value of job's env variable 2 is: $jobEnvVar_two"