name: "testing variable creation and sharing within a job"

on:
    push:
        branches: 
            - dev
        paths: 
            - 'testFolder/**'

jobs:
    testing_started:
        runs-on: ubuntu-latest
        
        outputs:
            myVar_one: ${{steps.setVariable.outputs.myVar1}}
            myVar_two: ${{steps.setVariable.outputs.myVar2}}
        
        steps:
            - name: checkout my code
              uses: actions/checkout@v3
            
            - name: set the variable
              id: 'setVariable'
              env:
                myVar1: "hi_Manoj"
              run: |
                echo "value of myVar1 is in step 1 is: $myVar1"
            
            - name: check the variable
              run: |
                echo "value of myVar1 is: $myVar1"